### ISSUE TITLE
Resolver problema dos dialogs

### ISSUE THREAD

**Issue by billjsan** [willjsan/gesTADS#6]
a resolução da issue #1 resultou em um bug no qual as telas de dialogo não são exibidas.
Na verdade elas são exibidas porém por um tempo muito curto e não dá tempo do usuário ver a tela de aviso.
Uma possível implementação inicial (gambiarra) seria usando o Thread.sleep(2000);

**Comment by PeuSouza** [comment]
vai ficar na gambiarra mesmo e vai ficar otimo
